[theme]
primaryColor = "#006494"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

# Adições para corrigir os avisos de "Invalid color" nos logs
widgetBackgroundColor = "#FFFFFF"
widgetBorderColor = "#D3D3D3"
skeletonBackgroundColor = "#F0F2F6"

[server]
headless = true
