# Exemplo. Não envie credenciais reais para o GitHub.

[service_account]
type = "service_account"
project_id = "SEU_PROJECT_ID"
private_key_id = "SEU_PRIVATE_KEY_ID"
private_key = "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
client_email = "firebase-adminsdk@SEU_PROJECT_ID.iam.gserviceaccount.com"
client_id = "SEU_CLIENT_ID"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "SEU_CLIENT_X509_CERT_URL"

[firebase]
apiKey = "SUA_API_KEY"
authDomain = "SEU_PROJECT.firebaseapp.com"
projectId = "SEU_PROJECT_ID"
storageBucket = "SEU_PROJECT.appspot.com"
messagingSenderId = "SEU_MESSAGING_SENDER_ID"
appId = "SEU_APP_ID"
databaseURL = ""
